name: Hello Agile

on:
  push:
    branches: [ dev ] // Trigger the workflow on push to the 'dev' branch
  pull_request:
    branches: [ main ] // Trigger the workflow on pull request to the 'main' branch

jobs:
  say_hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo "Hello from GitHub Actions!"